### ISSUE TITLE
Add support for float32

### ISSUE THREAD

**Issue by dizcza** [pwollstadt/IDTxl#36]
If we change data types to `float32`, `demo_core_estimators.py` doesn't work anymore.

```python
source_cor = np.random.normal(0, 1, size=n).astype(np.float32)  # correlated src
source_uncor = np.random.normal(0, 1, size=n).astype(np.float32)  # uncorrelated src
```

```
Traceback (most recent call last):
  File "/home/ulianych/PycharmProjects/other/IDTxl/demos/demo_core_estimators.py", line 43, in <module>
    cmi = est.estimate(source_cor, target, source_uncor)
  File "/home/ulianych/PycharmProjects/other/IDTxl/idtxl/estimators_jidt.py", line 466, in estimate
    self.calc.setObservations(var1, var2, cond)
RuntimeError: No matching overloads found for setObservations in find. at native/common/jp_method.cpp:127
```

**Comment by pwollstadt** [comment]
Hi @dizcza, the JAVA code you are calling in line 43 accepts only float64, this is expected behavior. Do you specifically want to process float32? You could use the GPU estimators, those operate on float32. If you want to stick with the JAVA estimators, you would have to convert your data to float64.

**Comment by pwollstadt** [comment]
I am closing this. Please reopen if necessary.
