### ISSUE TITLE
I meet an error when running demo_bivariate.py

### ISSUE THREAD

**Issue by GoForit-007** [pwollstadt/IDTxl#46]
Traceback (most recent call last):
  File "E:/寒假工作/因果关系/python代码/demos/demo_bivariate_te.py", line 18, in <module>
    results = network_analysis.analyse_network(settings=settings, data=data)
  File "E:\寒假工作\因果关系\python代码\idtxl\bivariate_te.py", line 155, in analyse_network
    settings, data, targets[t], sources[t])
  File "E:\寒假工作\因果关系\python代码\idtxl\bivariate_te.py", line 271, in analyse_single_target
    self._initialise(settings, data, sources, target)
  File "E:\寒假工作\因果关系\python代码\idtxl\network_inference.py", line 370, in _initialise
    self._set_cmi_estimator()
  File "E:\寒假工作\因果关系\python代码\idtxl\network_analysis.py", line 209, in _set_cmi_estimator
    self._cmi_estimator = EstimatorClass(self.settings)
  File "E:\寒假工作\因果关系\python代码\idtxl\estimators_jidt.py", line 1319, in __init__
    super().__init__(CalcClass, settings)
  File "E:\寒假工作\因果关系\python代码\idtxl\estimators_jidt.py", line 321, in __init__
    self.calc = CalcClass()
  File "C:\Python37\lib\site-packages\jpype\_jpackage.py", line 124, in __call__
    raise TypeError("Package {0} is not Callable".format(self._name))
TypeError: Package <Java package infodynamics.measures.continuous.gaussian.ConditionalMutualInfoCalculatorMultiVariateGaussian._name> is not Callable

**Comment by pwollstadt** [comment]
Hi, we had some trouble after an Update of JPype1 (see #38), which may cause this error. Thanks to a fix by @jlizier this should work in the newest release ([v1.1](https://github.com/pwollstadt/IDTxl/releases/tag/v1.1)) or by downgrading JPype1 to v0.6.3 as described in the [conda installation instructions](https://github.com/pwollstadt/IDTxl/wiki/Installation-and-Requirements#anaconda-installation). 

Let me know if that helped. Best, Patricia

**Comment by pwollstadt** [comment]
Will close this issue due to inactivity. Fell free to reopen if necessary.
