### ISSUE TITLE
Error end of the demo code.

### ISSUE THREAD

**Issue by sonurdogan** [pwollstadt/IDTxl#60]
I got this error while I'm trying to run demos/demo_bivariate_te.py
I used version of JPype1 (0.6.3)
....

sequential maximum statistic, n_perm: 500, testing 4 selected sources
final source samples: [(1, 1), (1, 2), (1, 4), (3, 1)]
final target samples: [(4, 1), (4, 4), (4, 2), (4, 3), (4, 5)]

	0 -> 2, max_te_lag: 3
	1 -> 3, max_te_lag: 2
	1 -> 4, max_te_lag: 1
	2 -> 0, max_te_lag: 3
	3 -> 1, max_te_lag: 3
	3 -> 4, max_te_lag: 1
	4 -> 1, max_te_lag: 2
	4 -> 3, max_te_lag: 5
Traceback (most recent call last):
  File "demos/demo_bivariate_te.py", line 22, in <module>
    plot_network(results=results, weights='max_te_lag', fdr=False)
  File "/Users/onurdogan/Documents/IDTxl/idtxl/visualise_graph.py", line 67, in plot_network
    _plot_graph(graph, ax1, weights)
  File "/Users/onurdogan/Documents/IDTxl/idtxl/visualise_graph.py", line 153, in _plot_graph
    nx.draw_circular(graph, with_labels=True, node_size=600, alpha=1.0,
  File "/Users/onurdogan/opt/anaconda3/envs/idtxl/lib/python3.8/site-packages/networkx/drawing/nx_pylab.py", line 1097, in draw_circular
    draw(G, circular_layout(G), **kwargs)
  File "/Users/onurdogan/opt/anaconda3/envs/idtxl/lib/python3.8/site-packages/networkx/drawing/nx_pylab.py", line 123, in draw
    draw_networkx(G, pos=pos, ax=ax, **kwds)
  File "/Users/onurdogan/opt/anaconda3/envs/idtxl/lib/python3.8/site-packages/networkx/drawing/nx_pylab.py", line 326, in draw_networkx
    raise ValueError(f"Received invalid argument(s): {invalid_args}")
ValueError: Received invalid argument(s): hold

**Comment by pwollstadt** [comment]
Just as a comment for other people stumbling over this: The hold argument was deprecated in newer versions of networkx. Please try updating the package if you experience similar issues.
